// Generated by CoffeeScript 2.4.1
(function() {
  "use strict";
  var builder, defaults, parser, processors;

  defaults = require('./defaults');

  builder = require('./builder');

  parser = require('./parser');

  processors = require('./processors');

  exports.defaults = defaults.defaults;

  exports.processors = processors;

  exports.ValidationError = class ValidationError extends Error {
    constructor(message) {
      super(message);
      this.message = message;
    }

  };

  exports.Builder = builder.Builder;

  exports.Parser = parser.Parser;

  exports.parseString = parser.parseString;

  exports.parseStringPromise = parser.parseStringPromise;

}).call(this);
